#!/usr/bin/env bash

SEED="$1"
shift

while [ "$1" ]; do
    SEED="${SEED} $1"
    shift
done

TOKEN=$(oathtool --base32 --totp "${SEED}")

echo -n "${TOKEN}"

if [ -x "$(which pbcopy)" ]; then
    echo -n "${TOKEN}" | pbcopy
    echo " (copied)"
else
    echo
fi


