#!/usr/bin/env bash

if [[ ! ("$#" == 1 || ("$#" == 3 && "$2" == 'in')) ]]; then
    echo "usage: all extension ['in' path]"
    exit 1
fi

FIND_PATH='.'
if [ "$3" ]; then
    FIND_PATH="$3"
fi

$EDITOR $(find "${FIND_PATH}" -ipath "*.$1")
