#!/bin/bash

if [ "$1" ]; then
    EXECUTABLE="$1"
    shift
else
    echo "usage: $(basename "$0") EXECUTABLE [COMMANDS...]" >&2
    exit 1
fi

if [ -f "$(proj-root)/Gemfile" ] && [ -x "$(which bundler)" ]; then
    bundle exec "${EXECUTABLE}" "$@"
else
    "${EXECUTABLE}" "$@"
fi
