#!/bin/bash

cd "$(proj-root)" || exit
if [ "$1" ]; then
    FILES=($(git status --porcelain | sed 's/^.. //' | grep "$1"))
else
    FILES=($(git status --porcelain | sed 's/^.. //' | grep "$1" | grep "$1"))
fi
${EDITOR} "${FILES[@]}"
