#!/bin/bash

cd $(proj-root)

WD='.'

if [[ "$#" != 1 ]] && [[ "$#" != 3 ]]; then
    echo 'usage: efind PREFIX [in DIRECTORY]'
    exit 1
fi

if [ -d "./src/" ]; then
    WD="./src/"
fi

if [[ "$2" == 'in' ]]; then
    WD="$3"
fi

FILES=$(find "$WD" -iname "$1*" | awk '{ print length, $0 }' | sort -g | cut -d' ' -f2)
FILE=$(echo "$FILES" | head -n 1)

${EDITOR} ${FILE}
