#!/bin/bash

cd "$(proj-root)" || exit 1

WD='.'
EXCLUDES='[.]((os)|o|(class))$'

if [[ "$1" == '-n' ]]; then
    DRY_RUN=true
    shift
fi

if [[ "$#" != 1 ]] && [[ "$#" != 3 ]]; then
    echo 'usage: efind SUBSTR [in DIRECTORY]' >/dev/stderr
    exit 1
fi

if [ -d "./src/" ]; then
    WD="./src/"
fi

if [[ "$2" == 'in' ]]; then
    WD="$3"
fi

SUBSTR="$1"
FILES=$(find "$WD" -iname "*${SUBSTR}*" | awk '{ print length, $0 }' | sort -g | cut -d' ' -f2 | egrep -v "${EXCLUDES}")
FILE=$(echo "$FILES" | head -n 1)

if [ "${DRY_RUN}" ]; then
    echo "${EDITOR} ${FILE}"
    exit
fi

if [ "${FILE}" ]; then
    ${EDITOR} "${FILE}"
else
    echo "Could not find any files for \"${SUBSTR}\"!" >/dev/stderr
    exit 2
fi
