#!/bin/bash

pylint --msg-template='{path}:{line}: {category} ({symbol}): {msg}' \
    --reports=n "$@" 2>/dev/null \
    | grep -v ': info'  \
    | sed -r 's/: ([a-z])/: \u\1/' \
    | tail -n +2
    
