#!/bin/bash


if [ "$(which pylint 2>/dev/null)" ]; then
    CMD=pylint
elif [ "$(which python3-pylint 2>/dev/null)" ]; then
    CMD=python3-pylint
else
    echo '0:0 no-bin (no-bin): failed to find pylint'
    exit 1
fi

$CMD --msg-template='{path}:{line}: {category} ({symbol}): {msg}' \
    --reports=n "$@" 2>/dev/null \
    | grep -v ': info'  \
    | sed 's/convention/Warning[convention]/' \
    | sed -r 's/: ([a-z])/: \u\1/' \
    | tail -n +2
    
