#!/bin/bash

cd $(git rev-parse --show-toplevel 2>/dev/null)

function check() {
    sbtc "$@" | \
    sed -r 's|\[error\] /|ERROR /|' | \
    sed -r 's/\[error\] //' | \
    sed -r 's/ERROR /[error] /' | \
    sed -r 's|\[warn\] /|WARN /|' | \
    sed -r 's/\[warn\] //' | \
    sed -r 's/WARN /[warn] /'
}

check test:compile
check scalastyle
check test:scalastyle
check styleCheck
check test:styleCheck
