#!/bin/bash

cd "$(git rev-parse --show-toplevel 2>/dev/null)" || exit

sbtc test:compile | \
    egrep '^(\[error\]|\[warn\])' | \
    sed -r 's|\[error\] /|ERROR /|' | \
    sed -r 's/\[error\] //' | \
    sed -r 's/ERROR /[error] /' | \
    sed -r 's|\[warn\] /|WARN /|' | \
    sed -r 's/\[warn\] //' | \
    sed -r 's/WARN /[warn] /' | \
    egrep -v '^(Total time:)|(errors exist$)' | \
    cat
