#!/usr/bin/env bash
# Requires Bash 4 which is newer than what OSX installs by default.

NO_HOME_PATH="$(echo "$PATH" | sed -s "s|$HOME/bin[^:]*:||g")"
EXERCISM_BIN=$(PATH="${NO_HOME_PATH}" which exercism)

if [[ "$1" == 'submit' ]] && [[ "$#" == 1 ]]; then

    # Swift support.
    if [ -f "Package.swift" ]; then
        readarray -d '' SOURCES < <(find "Sources" -type f -print0)
    fi

    "${EXERCISM_BIN}" submit "${SOURCES[@]}"
else
    "${EXERCISM_BIN}" "$@"
fi
