#!/usr/bin/env bash

if ! [ "$1" ]; then
    echo "Usage: gfm infile"
    exit 1
fi

OUTFILE="$(mktemp /tmp/gfm-preview-XXXX).html"

find "${PWD}" -maxdepth 1 -type d -exec ln -sf {} /tmp/ \;
if [ -h /tmp/.git ]; then
    rm /tmp/.git
fi

grip --export "$1" "${OUTFILE}"

open "${OUTFILE}"
