#!/bin/bash

if ! [ "$1" ]; then
    echo "Usage: gfm infile"
    exit 1
fi

OUTFILE="$(mktemp /tmp/gfm-preview-XXXX).html"

find "${PWD}" -type d -maxdepth 1 -exec ln -sf {} /tmp/ \;

grip --export "$1" "${OUTFILE}"

open "${OUTFILE}"
