#!/usr/bin/env bash

ORIGIN_HOST_REGEXP='(github.com)|(github-personal)'

if [ ! "$(command -v git 2>/dev/null)" ]; then
    exit 1
fi

results=$(git rev-parse --git-dir 2>&1)
git_dir=${results}

if echo "$results" | grep -q '^fatal:'; then
    exit 1
fi

branch=$(git branch 2> /dev/null | grep -E '^[*] ' | sed -r 's/^[*] //')

if [ -e "${git_dir}/FETCH_HEAD" ] && \
       [ "$(find "${git_dir}/FETCH_HEAD" -mmin +5)" ]; then
    git fetch --all >/dev/null 2>/dev/null
fi

# Prevent unexpected delays while working.
touch "${git_dir}/FETCH_HEAD" 2>/dev/null

git_version=$(git --version | sed 's/git version //')
git_major_version=$(echo "${git_version}" | cut -d. -f1)
git_minor_version=$(echo "${git_version}" | cut -d. -f2)

# Legacy git support, a little crude; also somewhat prone to breakage.
if [ "${git_major_version}" -gt '1' ] || [ "${git_minor_version}" -gt '8' ]; then
    header=$(git status | tail -n +2 | head -n 1)
    behind=$(echo "${header}" | grep -i 'behind')
    ahead=$(echo "${header}" | grep -i 'ahead')
    diverged=$(echo "${header}" | grep -i 'diverged')
else
    header=$(git status --porcelain --branch | head -n 1)
    behind=$(echo "${header}" | grep -E '\[behind [0-9]+\]')
    ahead=$(echo "${header}" | grep -E '\[ahead [0-9]+\]')
    diverged=$(echo "${header}" | grep -E "\[ahead [0-9]+, behind [0-9]+\]")
fi

REF="$(git symbolic-ref -q HEAD)"
if [ -z "$(git for-each-ref --format='%(upstream:short)' "${REF}")" ]; then
    no_upstream='?'
fi

changes=$(git status --porcelain | wc -l | tr -d ' ')

stashes=$(git stash list)

origin_host=$(git config --get remote.origin.url | \
                     sed -r 's/^.*@//' | \
                     sed -r 's|^https?://||' | \
                     sed -r 's/:.*$//')

if echo "${origin_host}" | grep -v -q -E "${ORIGIN_HOST_REGEXP}"; then
    unknown_origin=true
fi

if [ -z "${origin_host}" ]; then
    origin_host='no-origin'
    unknown_origin=true
fi

if [[ "${changes}" != 0 ]]; then
    if git status --porcelain 2>/dev/null | grep -E -v -q '^. '; then
        dirty='*'
    else
        dirty='~'
    fi
fi

if [ "$behind" ]; then
    remote='-'
fi

if [ "${ahead}" ]; then
    local='+'
fi

if [ "${diverged}" ]; then
    local='+'
    remote='-'
fi

if [ "${stashes}" ]; then
    stash='&'
fi

if [ "${unknown_origin}" ]; then
    branch="${origin_host}/${branch}"
fi

echo -n "${branch}${no_upstream}${local}${remote}${dirty}${stash}"
