#!/usr/bin/env bash

ORIGIN_HOST_REGEXP='(github.com)|(github-personal)'

if [ ! "$(command -v git 2>/dev/null)" ]; then
    exit 1
fi

GIT_DIR=$(git rev-parse --git-dir 2>&1)

if echo "$GIT_DIR" | grep -q '^fatal:'; then
    exit 1
fi

if [ -e "${GIT_DIR}/FETCH_HEAD" ] && \
       [ "$(find "${GIT_DIR}/FETCH_HEAD" -mmin +5)" ]; then
    git fetch >/dev/null 2>/dev/null
fi

# Prevent unexpected delays while working.
touch "${GIT_DIR}/FETCH_HEAD" 2>/dev/null

FULL_STATUS=$(git status --porcelain --branch)

HEADER=$(echo "${FULL_STATUS}" | head -n 1)
STATUS=$(echo "${FULL_STATUS}" | tail -n +2)

BRANCH=$(echo "$HEADER" | sed -r 's/^## ([^.]+).*/\1/')

BEHIND=$(echo "${HEADER}" | grep -E '\[behind [0-9]+\]')
AHEAD=$(echo "${HEADER}" | grep -E '\[ahead [0-9]+\]')
DIVERGED=$(echo "${HEADER}" | grep -E "\[ahead [0-9]+, behind [0-9]+\]")

if [ -z "$(git config "branch.${BRANCH}.remote")" ]; then
    NO_UPSTREAM='?'
fi

CHANGES=$(echo -n "${STATUS}" | wc -c | tr -d ' ')

STASHES=$(git stash list)

ORIGIN_HOST=$(git config --get remote.origin.url | \
                  sed -r 's/^.*@//' | \
                  sed -r 's|^https?://||' | \
                  sed -r 's/:.*$//')

if echo "${ORIGIN_HOST}" | grep -v -q -E "${ORIGIN_HOST_REGEXP}"; then
    UNKNOWN_ORIGIN=true
fi

if [ -z "${ORIGIN_HOST}" ]; then
    ORIGIN_HOST='no-origin'
    if [[ "${BRANCH}" == "No commits yet on master" ]]; then
        BRANCH='no-commits'
    fi
    UNKNOWN_ORIGIN=true
fi

if [[ "${CHANGES}" != 0 ]]; then
    if echo "${STATUS}" | grep -E -v -q '^. '; then
        DIRTY='*'
    else
        DIRTY='~'
    fi
fi

if [ "${BEHIND}" ]; then
    REMOTE='-'
fi

if [ "${AHEAD}" ]; then
    LOCAL='+'
fi

if [ "${DIVERGED}" ]; then
    LOCAL='+'
    REMOTE='-'
fi

if [ "${STASHES}" ]; then
    STASH='&'
fi

if [ "${UNKNOWN_ORIGIN}" ]; then
    if [ "${BRANCH}" ]; then
        BRANCH="${ORIGIN_HOST}/${BRANCH}"
    else
        BRANCH="${ORIGIN_HOST}/master"
    fi
fi

echo -n "${BRANCH}${NO_UPSTREAM}${LOCAL}${REMOTE}${DIRTY}${STASH}"
