#!/usr/bin/env bash

oldx=$(tput cols)
oldy=$(tput lines)
x=$((oldx * 100 / 70))
y=$((oldy * 100 / 70))

# Normalize to return to 24x80
if [[ 70 -lt $x && $x -lt 90 ]]; then
    x=80
    # y=24
fi

if [[ 20 -lt $y && $y -lt 28 ]]; then
    # x=80
    y=24
fi

resize $x $y
