#!/bin/bash

if ! [ "$1" ]; then
    echo 'usage: loop [-k] COMMAND'
fi

if [ "$1" = '-k' ]; then
    KILL=true
    shift
fi

EXCLUDES='(.*/[.].*)|(.*/flycheck_.*)|(.*[.]pyc[.]?[0-9]*)|(.*/htmlcov/.*)'

LOOP_COMMAND="$@"

(${LOOP_COMMAND}) &
PID="$!"

trap 'kill $PID' SIGINT SIGTERM EXIT

while read -r -d ""; do
    if $KILL; then
        kill "${PID}" 2>/dev/null
    fi
    echo
    (${LOOP_COMMAND}) &
    export PID="$!"
done < <(fswatch -E -e "${EXCLUDES}" -0 .)
