#!/bin/bash

EXCLUDES='(.*/[.].*)|(.*/flycheck_.*)|(.*[.]pyc[.]?[0-9]*)|(.*/htmlcov/.*)'

LOOP_COMMAND="$@"

(${LOOP_COMMAND}) &
PID="$!"

trap 'kill $PID' SIGINT SIGTERM EXIT

while read -d ""; do
    kill "${PID}" 2>/dev/null
    echo
    (${LOOP_COMMAND}) &
    export PID="$!"
done < <(fswatch -E -e "${EXCLUDES}" -0 .)
