#!/bin/bash

if [ "$#" -lt 2 ]; then
    echo 'usage: multi-ssh [user@]hostname... [command]'
    exit
fi

HOSTS=()
while [ "$2" ]; do
    HOSTS+=("$1")
    shift
done
CMD="$1"

PIDS=""

for host in ${HOSTS[*]}; do
    # shellcheck disable=SC2029
    ssh -o StrictHostKeyChecking=no "$host" "$CMD" & 
    PIDS="$PIDS $!"
done

trap 'kill $PIDS' SIGINT

wait
