#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
    echo 'usage: newscript SCRIPTNAME'
    exit
fi

if ! [ -e "$1" ]; then
    echo '#!/usr/bin/env bash' >"$1"
    echo >> "$1"
fi

chmod +x "$1"
emacs "$1"
