#!/usr/bin/env bash

die () {
    echo
    echo "$1"
    exit 1
}

if ! [ "$1" ]; then
    die 'Usage: pw [-p CRYPT_FILE] KEY [AFTER-CONTEXT]'
fi

CRYPT_FILE=~/Documents/passwords.aes

if [[ "$1" == '-p' ]]; then
    shift                       # eat '-p'
    CRYPT_FILE="$1"
    shift                       # eat $CRYPT_FILE
fi

if ! [ -f "${CRYPT_FILE}" ]; then
    die "pw: error ${CRYPT_FILE} does not exist!"
fi

after=1

if [ "$2" ]; then
    after="$2"
fi

read -r -p 'Enter decryption password: ' -s password
if [ "$PS1" ]; then
    echo
fi

cleartext=$(openssl aes-256-cbc -d -md md5 \
                    -in "${CRYPT_FILE}" \
                    -pass "pass:${password}" 2>/dev/null | tr -d '\0' 2>/dev/null) || \
    die 'Failed to decrypt!'

if [[ "$1" == '-e' ]]; then
    TMP=$(TMPDIR=/tmp/ mktemp -t 'tempXXX') || die 'Failed to create tmp file!'
    echo "$cleartext" > "${TMP}"
    "${EDITOR}" "${TMP}"
    openssl aes-256-cbc \
            -md md5 \
            -in "${TMP}" \
            -out "${CRYPT_FILE}" \
            -pass "pass:${password}"
    rm "${TMP}"
else
    export LESS=''
    ORIG=$(echo "${cleartext}" | grep -i "$1" -A "${after}")
    ORIG_ENTRIES=$(echo "${ORIG}" | grep -c '^[^ ]')

    TEXT="${ORIG}"
    ENTRIES="${ORIG_ENTRIES}"
    
    while [ "${ENTRIES}" -gt 0 ] \
              && [ "${after}" -lt 10 ] \
              && [[ "${ENTRIES}" == "${ORIG_ENTRIES}" ]]; do
        after=$((after + 1))
        TEXT=$(echo "${cleartext}" | grep -i "$1" -A "${after}")
        ENTRIES=$(echo "${TEXT}" | grep -c '^[^ ]')
    done

    after=$((after - 1))
    if [ "${ENTRIES}" -gt 0 ]; then
        echo
        echo "${cleartext}" | grep -i "$1" -A "${after}" | less
    else
        echo
    fi
fi
