#!/bin/bash

# Generate tags using exuberant c-tags for the root directory of the
# repository (only supports git), with fallback to the current directory.
ROOT=$(proj-root)

if [ -z "$ROOT" ]; then
    exit 1
fi

cd "$ROOT" || exit 1

ctags --exclude=.git --exclude=target --exclude=*/target --exclude=node_modules --exclude='flycheck_*' -e -R -f .tags .

# We're done if we don't have /target.
if ! [ -d 'target' ]; then
    exit
fi

# Scala dep-tags setup.
DEP_ROOT="${PWD}/.deps"
DEP_TAGS=".dep-tags"

mkdir -p "${DEP_ROOT}"

find . -maxdepth 4 -name 'sbt-ctags-dep-srcs' | while read -r SRC_DEP_DIR; do
    DEP_DIR=$(dirname "$(dirname "${SRC_DEP_DIR}")")
    if [ "${DEP_DIR}" = '.' ]; then
        DEP_DIR='root-proj'
    fi
    DEP_DIR="${DEP_ROOT}/${DEP_DIR}"

    if [ ! -L "${SRC_DEP_DIR}" ] && [ -d "${SRC_DEP_DIR}" ]; then
        mv "${SRC_DEP_DIR}" "${DEP_DIR}"
    fi
done

find .deps/* -maxdepth 0 | while read -r DEP_DIR; do
    SRC_DEP_BASE=$(basename "${DEP_DIR}")
    if [ "${SRC_DEP_BASE}" = 'root-proj' ]; then
        SRC_DEP_BASE='.'
    fi

    DEP_DIR="${PWD}/${DEP_DIR}"
    SRC_DEP_DIR="${PWD}/${SRC_DEP_BASE}/target/sbt-ctags-dep-srcs"

    ln -s "${DEP_DIR}" "${SRC_DEP_DIR}" 2>/dev/null
done

if [ ! -f "${DEP_TAGS}" ] && [ -d "${DEP_ROOT}" ]; then
    ctags -e -R -f "${DEP_TAGS}" "${DEP_ROOT}"/* "${DEP_ROOT}"/*/*
fi

if [ -f "${DEP_TAGS}" ]; then
    cat -fr "${DEP_TAGS}" >> .tags
fi
