#!/bin/bash

# Generate tags using ripper-tags for the root directory of the
# repository (only supports git), with fallback to the current directory.
ROOT=$(proj-root)

if [ -z "$ROOT" ] || [ "$ROOT" == "$HOME" ]; then
    exit 1
fi

cd "$ROOT" || exit 1

ripper-tags -R -e --exclude=vendor -f "$(proj-root)/.tags"
