#!/bin/bash

# Generate tags using exuberant c-tags for the root directory of the
# repository (only supports git), with fallback to the current directory.  
ROOT=$(proj-root)

if [ "$ROOT" ]; then
    cd $ROOT
fi

ctags --exclude=.git --exclude=target --exclude=node_modules -e -R -f .tags .

DEP_TAGS='.dep-tags'
if [ -z "${DEP_DIR}" ]; then
    DEP_DIR='target/sbt-ctags-dep-srcs/'
fi

if [ ! -f "$DEP_TAGS" ] && [ -d "$DEP_DIR" ]; then
    ctags -e -R -f "$DEP_TAGS" "$DEP_DIR"
fi

if [ -f "${DEP_TAGS}" ]; then
    cat "${DEP_TAGS}" >> .tags
fi
