#!/usr/bin/env bash

x=80
y=24

if [[ "$1" == "--no-clear" || "$1" == "-n" ]]; then
    noclear="true"
    shift
fi

if [ "$1" ]; then
    x="$1"
fi

if [ "$1" ]; then
    y="$2"
fi

echo -e "\e[8;$y;$x;t"
if [[ ! "$noclear" ]]; then
    tput clear
fi
