#!/bin/bash

PROJ_ROOT=$(git rev-parse --show-toplevel 2>/dev/null)

sbtd >/dev/null
SESSION=$(sbtd)

if [[ "$#" < 1 ]]; then
   echo "usage: sbtc COMMAND..."
   exit
fi

COMMAND=";$1"
shift
while [ "$1" ]; do
    COMMAND="$COMMAND ;$1"
    shift
done

COMMAND=$(echo "$COMMAND" | sed 's/;;/;/')

if [ $(echo "$COMMAND" | grep '~') ]; then
    echo "Repeated commands (~COMMAND) are not supported."
    exit 1
fi

TMP="/tmp/sbtd/$SESSION"
MSG='Starting daemon'
until grep '^> $' $TMP >/dev/null; do
    echo -n "$MSG"
    MSG='.'
    sleep 1
done

if [[ "$MSG" == '.' ]]; then
    echo ' done.'
    echo
    sleep 0.3
fi

tmux send -t "$SESSION" "$COMMAND" ENTER
tmux send -t "$SESSION" ENTER
tmux send -t "$SESSION" ENTER

FIRST='true'
tail -f -n 0 "$TMP" | \
    while read LOGLINE; do
        LOGLINE=$(echo "$LOGLINE" | tr -d '\r')
        if [[ "${LOGLINE}" == "> " ]]; then
            exit
        fi

        if [[ "${LOGLINE}" != "$COMMAND" ]]; then
            echo "$LOGLINE"
        fi
    done
