#!/bin/bash

if ! ssh -qT vamp-willow exit; then
    VBoxManage startvm vamp-willow --type headless
fi

until ssh -qT vamp-willow exit; do
    sleep 0.1
done

if ! [ -f ~/Developer/.mounted ]; then
    ssh -CnfN -D 26499 vamp-willow
    sshfs -o volname=Developer vamp-willow:Developer ~/Developer
fi
