modmap:
  - name: Global
    remap:
      Super_L: Ctrl_L
      Super_R: Ctrl_R
      Capslock: Super_L
      Ctrl_L: Super_L

  - name: Terminal
    application:
      only: [Gnome-terminal, Guake]
    remap:
      Alt_R: Super_R

keymap:
  - name: Global
    remap:
      C-space: Super-space

  - name: Emacs
    application:
      not: [Gnome-terminal, Guake]
    exact_match: true
    remap:
      Super-b: left
      Super-f: right
      Super-p: up
      Super-c: down
      M-b: C-left
      M-f: C-right
      Super-a: home
      Super-e: end
      Super-d: delete
      M-d: C-delete
      Super-k: [Shift-end, C-x]
      Super-slash: C-z
      Super-s: C-f
      M-left: C-left
      M-right: C-right
      M-Shift-left: Shift-C-left
      M-Shift-right: Shift-C-right
      M-backspace: C-backspace
      C-backspace: [Shift-home, backspace]

  - name: Firefox
    application:
      only: firefox
    remap:
      Ctrl-1: M-1
      Ctrl-2: M-2
      Ctrl-3: M-3
      Ctrl-4: M-4
      Ctrl-5: M-5
      Ctrl-6: M-6
      Ctrl-7: M-7
      Ctrl-8: M-8
      Ctrl-9: M-9
      Super-tab: C-pagedown
      Super-Shift-tab: C-pageup
      C-left: M-left
      C-right: M-right

  - name: Terminal
    application:
      only: [Gnome-terminal, Guake]
    remap:
      Super-1: C-1
      Super-2: C-2
      Super-3: C-3
      Super-4: C-4
      Super-5: C-5
      Super-6: C-6
      Super-7: C-7
      Super-8: C-8
      Super-9: C-9
      Super-0: C-0
      Super-minus: C-minus
      Super-equal: C-equal
      Super-leftbrace: C-leftbrace
      Super-rightbrace: C-rightbrace
      Super-backslash: C-backslash
      Super-semicolon: C-semicolon
      Super-apostrophe: C-apostrophe
      Super-comma: C-comma
      Super-dot: C-dot
      Super-a: C-a
      Super-b: C-b
      Super-c: C-c
      Super-d: C-d
      Super-e: C-e
      Super-f: C-f
      Super-g: C-g
      Super-h: C-h
      Super-i: C-i
      Super-j: C-j
      Super-k: C-k
      Super-l: C-l
      Super-m: C-m
      Super-n: C-n
      Super-o: C-o
      Super-p: C-p
      Super-q: C-q
      Super-r: C-r
      Super-s: C-s
      Super-t: C-t
      Super-u: C-u
      Super-v: C-v
      Super-w: C-w
      Super-x: C-x
      Super-y: C-y
      Super-z: C-z
      Super-slash: C-slash
      Super-space: C-space
      C-1: Super-1
      C-2: Super-2
      C-3: Super-3
      C-4: Super-4
      C-5: Super-5
      C-6: Super-6
      C-7: Super-7
      C-8: Super-8
      C-9: Super-9
      C-0: Super-0
      C-minus: Super-minus
      C-equal: Super-equal
      C-a: Super-a
      C-b: Super-b
      C-c: Super-c
      C-d: Super-d
      C-e: Super-e
      C-f: Super-f
      C-g: Super-g
      C-h: Super-h
      C-i: Super-i
      C-j: Super-j
      C-k: Super-k
      C-l: Super-l
      C-m: Super-m
      # C-n: Super-n
      C-o: Super-o
      C-p: Super-p
      C-q: Super-q
      C-r: Super-r
      C-s: Super-s
      C-t: Super-t
      C-u: Super-u
      C-v: Super-v
      C-w: Super-w
      C-x: Super-x
      C-y: Super-y
      C-z: Super-z
      Super-enter: C-j
      C-Super-t: C-Super-t

  - name: Gnome Terminal
    application:
      only: Gnome-terminal
    remap:
      C-n: C-Super-t
      C-Shift-n: Super-n

  - name: Guake
    application:
      only: Guake
    remap:
      C-n: C-Super-t
