#!/usr/bin/env bash

DEST="${HOME}/"
INSTALL_CMD='ln -s -i'

if [ "$1" ]; then
    DEST="$1:"
    INSTALL_CMD='scp'
fi

${INSTALL_CMD} \
    "${PWD}"/.bash* \
    "${PWD}"/.profile \
    "${PWD}"/.inputrc \
    "${PWD}"/.git* \
    "${DEST}"

if [[ "$(uname)" == 'Linux' ]]; then
    ${INSTALL_CMD} "${PWD}"/.xremap-config.yml "${DEST}"
    ${INSTALL_CMD} "${PWD}"/xremap.desktop ~/.config/autostart/
    mkdir -p ~/.config/systemd/user/
    ${INSTALL_CMD} "${PWD}"/xremap.service ~/.config/systemd/user/
fi


mkdir -p "${DEST}/.gnupg/"
${INSTALL_CMD} "${PWD}"/gpg.conf "${DEST}/.gnupg/"
${INSTALL_CMD} "${PWD}"/gpg-agent.conf "${DEST}/.gnupg/"

if [[ "$(uname)" == 'Darwin' ]]; then
    mkdir -p "${DEST}/.gnupg"
    ${INSTALL_CMD} "${PWD}"/gpg-agent-osx.conf "${DEST}/.gnupg/gpg-agent.conf"
fi
