#!/bin/bash

DEST="${HOME}/"
INSTALL_CMD='ln -s -v'
if [[ "$(uname)" == 'Darwin' || "$(uname)" == 'Linux' ]]; then
    INSTALL_CMD='ln -s -i'
fi

if [ "$1" ]; then
    DEST="$1:"
    INSTALL_CMD='scp'
fi


${INSTALL_CMD} "${PWD}"/.bash* "${PWD}"/.profile "${DEST}"
