#!/usr/bin/env bash

URL="$1"
FILE="$2"

# curl --header "Content-Type: application/json" --user 'engineering@socrata.com:OpenData!' --request POST --data @"$FILE" "$URL"
curl --header "Content-Type: application/json" --request POST --data @"$FILE" "$URL"
echo
