#!/bin/bash

# Mute sound.
osascript -e 'set volume output muted true'

# Auto-hide dock.
osascript -e "tell application \"System Events\" to set the autohide of the dock preferences to true"

# Do bounce.
defaults write com.apple.dock no-bouncing -bool FALSE
killall Dock
