#!/bin/bash

JAVA_HOME=$(/usr/libexec/java_home -v 1.7) exec java -Dfile.encoding="ISO-8859-1" -XX:MaxPermSize=512m -Xmx2048M ${SBT_OPTS} -jar /usr/local/Library/LinkedKegs/sbt/libexec/sbt-launch.jar "$@"
