#!/usr/bin/env bash

if ! ssh -qT vamp-willow exit; then
    VBoxManage startvm vamp-willow --type headless
fi

until ssh -qT vamp-willow exit; do
    sleep 0.1
done

if ! nc -z localhost 26499 2>/dev/null; then
    ssh -CnfN -D 26499 vamp-willow
fi

if ! [ -f ~/Developer/.mounted ]; then
    sshfs -o volname=Developer vamp-willow:Developer ~/Developer 2>/dev/null
fi
