#!/bin/bash

SYM_LINK='ln -s -v'
if [[ "$(uname)" == 'Darwin' || "$(uname)" == 'Linux' ]]; then
    SYM_LINK='ln -s -i'
fi

${SYM_LINK} .bash* .profile ${HOME}/
${SYM_LINK} .profile ${HOME}/.bash_profile
